services:
  app:
    build: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/task
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=abc123abc
    container_name: taskmanager-api
    ports:
      - "8081:8080"
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: task
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abc123abc
    ports:
      - 5431:5432
