spring.application.name=Application

# PostgreSQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

# Error handling
spring.web.error.include-message=always
spring.web.error.include-binding-errors=always

jwt.secret=cetteChaineDoitFaireAuMoins32CaracteresPourEtreValide

spring.security.oauth2.client.registration.google.client-id=*********************
spring.security.oauth2.client.registration.google.client-secret=*************************

spring.security.oauth2.client.registration.github.client-id=*****************
spring.security.oauth2.client.registration.github.client-secret=******************************************************